name: build-soda
on:
  push:
    branches:
      - 'soda'
  workflow_dispatch:
env:
  VERSION: 8.0-2
  BRANCH: experimental_8.0
jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v2

      - name: setup
        working-directory: /home/runner/work/
        run: |
          mkdir -p /home/runner/.config/frogminer/
          sudo apt purge -y ubuntu-advantage-tools
          sudo dpkg --add-architecture i386 && sudo apt update
          sudo apt install aptitude
          sudo aptitude remove -y '?narrow(?installed,?version(deb.sury.org))'

      - name: clone wine-tkg-git repo
        working-directory: /home/runner/work/
        run: git clone https://github.com/Frogging-Family/wine-tkg-git.git

      - name: get/set the soda recipe
        working-directory: /home/runner/.config/frogminer/
        run: |
          curl https://raw.githubusercontent.com/bottlesdevs/build-tools/main/runners/vaniglia/wine-tkg-valve.cfg > wine-tkg.cfg
          sed -i "s/_plain_version=\"\"/_plain_version=\"$BRANCH\"/g" wine-tkg.cfg

      - name: start build
        working-directory: /home/runner/work/wine-tkg-git/wine-tkg-git/
        run: yes|./non-makepkg-build.sh

      - name: package
        working-directory: /home/runner/work/wine-tkg-git/wine-tkg-git/non-makepkg-builds/
        run: |
          mv wine-tkg-* soda-$VERSION-x86_64
          tar cJvf soda-$VERSION-x86_64.tar.xz soda-$VERSION-x86_64
          mv soda-$VERSION-x86_64.tar.xz /tmp/soda-$VERSION-x86_64.tar.xz

      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          automatic_release_tag: "soda-${{ env.VERSION }}"
          title: "Soda ${{ env.VERSION }}"
          files: "/tmp/soda-${{ env.VERSION }}-x86_64.tar.xz"
